name:                realw
version:             0.1.3.2
synopsis:            "Real World Haskell"
description:         "Please see the README on GitHub at <https://github.com/erlnow/realh#readme>"
# homepage:            https://github.com/erlnow/realw#readme
# -- bug-reports:
github:              "erlnow/realw"
license:             BSD3
license-file:        LICENSE
author:              Eduardo Ramón Lestau
maintainer:          erlestau@gmail.com
copyright:           "(c) 2020-2030 Eduardo Ramón Lestau"
category:            Learning
build-type:          Simple

extra-source-files:
  - ChangeLog.md
  - README.md
  - TODO
  - LICENSE
  - data/*

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  -Wall

library:
  source-dirs: src

executables:
  sample:
    source-dirs: app/sample
    main: Main.hs
    dependencies:
      - realw
  WC:
    source-dirs: app/Ch01
    main: Main.hs

tests:
  sample-test:
    source-dirs: test
    main: MyLibTest.hs
    dependencies:
      - realw
  realh-test:
    source-dirs: test/spec
    main: Spec.hs
    dependencies:
      - realw
      - hspec == 2.*
      - QuickCheck
    build-tools: hspec-discover
  doctest:
    source-dirs: test/doctest
    main: Main.hs
    dependencies:
      - realw
      - doctest >= 0.8
      - QuickCheck
